[tools]
python = "3.14"

[env]
_.python.venv = {path = ".venv", create = true, uv_create_args = ["--seed"]}

[tasks.setup]
run = """
pip install torch torchvision --index-url https://download.pytorch.org/whl/cu130
pip install -e .
"""